### ISSUE TITLE
Pie slices don't look proportional

### ISSUE THREAD

**Issue by dimus** [simonh1000/elm-charts#5]
`pie` chart in version 3.0.3 seem to generate slices that do not correspond to their values
![pie](https://cloud.githubusercontent.com/assets/12124/20804265/dcaf0544-b7b7-11e6-8380-8d56e12dede9.png)

**Comment by simonh1000** [comment]
Sorry, will work on a fix. I have a feeling that the line chart and pie
chart work oppositely and so when I fix one I break the other....

**Comment by simonh1000** [comment]
Would you be willing to try the files in the dev branch https://github.com/simonh1000/elm-charts/tree/dev/src and tell whether that helps

**Comment by simonh1000** [comment]
Actually I've published this change anyway. Turned out https://github.com/simonh1000/elm-charts/pull/4 had somehow not managed to make it into the published package
